# fractalchain/kubernetes/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fractal-ingress
  namespace: fractalchain
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - rpc.fractalchain.io
    - api.fractalchain.io
    secretName: fractal-tls
  rules:
  - host: rpc.fractalchain.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fractal-rpc
            port:
              number: 8593
  - host: api.fractalchain.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fractal-rpc
            port:
              number: 8593